name: build
on: [push]

env:
  ENGINE: pdflatex
  FILE: cv

jobs:
  build-main:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install LaTeX packages
        run: |
          tlmgr update --self
          tlmgr install sourcesanspro fontawesome5 enumitem paracol changepage needspace lastpage bookmark eso-pic
      - name: Compile PDF
        run: |
          latexmk -pdf -pdflatex="${{ env.ENGINE }} --shell-escape %O %S" ${{ env.FILE }}
      - name: Move
        run: mkdir -p artifacts && mv ${{ env.FILE }}.pdf ./artifacts/
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./artifacts/${{ env.FILE }}.pdf

  deploy:
    needs: [build-main]
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download main pdf
        uses: actions/download-artifact@v4
        with:
          name: artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./${{ env.FILE }}.pdf
